Class {
	#name : 'RwAbstractCluster',
	#superclass : 'Object',
	#instVars : [
		'name',
		'condition',
		'packageNames'
	],
	#category : 'RowancelloSample1-Rowan-Classes'
}

{ #category : 'accessing' }
RwAbstractCluster >> condition [
	^condition

]

{ #category : 'accessing' }
RwAbstractCluster >> condition: newValue [
	condition := newValue

]

{ #category : 'accessing' }
RwAbstractCluster >> name [
	^name

]

{ #category : 'accessing' }
RwAbstractCluster >> name: newValue [
	name := newValue

]

{ #category : 'accessing' }
RwAbstractCluster >> packageNames [
	^packageNames

]

{ #category : 'accessing' }
RwAbstractCluster >> packageNames: newValue [
	packageNames := newValue

]
