Class {
	#name : 'RwConvertComponentsToClustersTest',
	#superclass : 'TestCase',
	#category : 'RowancelloSample1-RowanKernel-Extensions-Tests'
}

{ #category : '0024' }
RwConvertComponentsToClustersTest >> testLoadComponent [
"RwTestProjectLibraryGenerator>>_addDefinitionsFor_0024:"
]

{ #category : '0024' }
RwConvertComponentsToClustersTest >> testPlatformNestedProjectLoadComponentV2 [
"RwTestProjectLibraryGenerator>>_addDefinitionsFor_0024:"
]

{ #category : '0024' }
RwConvertComponentsToClustersTest >> testPlatformSubcomponent [
"RwTestProjectLibraryGenerator>>_addDefinitionsFor_0024:"
]

{ #category : '0032' }
RwConvertComponentsToClustersTest >> testSimpleNestedProjectLoadComponentV2 [
"RwTestProjectLibraryGenerator>>_addDefinitionsFor_0032:"
]

{ #category : '0024' }
RwConvertComponentsToClustersTest >> testSimpleProjectLoadComponentV2 [
"RwTestProjectLibraryGeneratorV3>>_addDefinitionsFor_0085:"
]

{ #category : '0032' }
RwConvertComponentsToClustersTest >> testSubcomponent [
"RwTestProjectLibraryGenerator>>_addDefinitionsFor_0032:"
]
